=== SollyTaylor/mulphys/installer/packages/com.aossci.core/data/surrogate_model_input_interpreter.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type" : "object",
	"definitions" : {
		"def_samples" : {
			"type" : "array",
			"items" : {
				"type" : "array",
				"items" : {
					"type" : "number"
				},
				"minItems" : 1
			},
			"minItems" : 1
		}
	},
	"properties" : {
		"x_samples" : {
			"$ref" : "#/definitions/def_samples"
		},
		"y_samples" : {
			"$ref" : "#/definitions/def_samples"
		},
		"x_inputs" : {
			"type" : "array",
			"items" : {
				"type" : "number"
			}
		},
		"configurations" : {
			"type" : "object"
		}
	},
	"required" : ["x_samples", "y_samples", "x_inputs", "configurations"]
}

=== SollyTaylor/mulphys/installer/packages/com.aossci.core/data/python_codebase/surrogate_model_input.json
{
    "configurations": {
        "Polynomial_Order": "Quadratic",
        "Weight_Distance_Coefficient": 2,
        "Correlation_Function": "Spherical"
    },
    "x_inputs": [
        38,
        54
    ],
    "x_samples": [
        [
            28,
            28.2020202020202,
            28.404040404040405,
            28.606060606060606,
            28.80808080808081,
            29.01010101010101,
            29.21212121212121,
            29.414141414141415,
            29.616161616161616,
            29.81818181818182,
            30.02020202020202,
            30.22222222222222,
            30.424242424242426,
            30.626262626262626,
            30.828282828282827,
            31.03030303030303,
            31.232323232323232,
            31.434343434343432,
            31.636363636363637,
            31.838383838383837,
            32.04040404040404,
            32.24242424242424,
            32.44444444444444,
            32.64646464646464,
            32.84848484848485,
            33.05050505050505,
            33.25252525252525,
            33.45454545454545,
            33.656565656565654,
            33.858585858585855,
            34.06060606060606,
            34.26262626262626,
            34.464646464646464,
            34.666666666666664,
            34.868686868686865,
            35.07070707070707,
            35.27272727272727,
            35.474747474747474,
            35.676767676767675,
            35.87878787878788,
            36.08080808080808,
            36.282828282828284,
            36.484848484848484,
            36.686868686868685,
            36.888888888888886,
            37.09090909090909,
            37.292929292929294,
            37.494949494949495,
            37.696969696969695,
            37.898989898989896,
            38.101010101010104,
            38.303030303030305,
            38.505050505050505,
            38.70707070707071,
            38.90909090909091,
            39.111111111111114,
            39.313131313131315,
            39.515151515151516,
            39.717171717171716,
            39.91919191919192,
            40.121212121212125,
            40.32323232323232,
            40.525252525252526,
            40.72727272727273,
            40.92929292929293,
            41.131313131313135,
            41.333333333333336,
            41.535353535353536,
            41.73737373737374,
            41.93939393939394,
            42.141414141414145,
            42.34343434343434,
            42.54545454545455,
            42.74747474747475,
            42.94949494949495,
            43.151515151515156,
            43.35353535353535,
            43.55555555555556,
            43.75757575757576,
            43.95959595959596,
            44.161616161616166,
            44.36363636363636,
            44.56565656565657,
            44.76767676767676,
            44.96969696969697,
            45.17171717171718,
            45.37373737373737,
            45.57575757575758,
            45.77777777777778,
            45.97979797979798,
            46.18181818181819,
            46.38383838383838,
            46.58585858585859,
            46.78787878787878,
            46.98989898989899,
            47.1919191919192,
            47.39393939393939,
            47.5959595959596,
            47.7979797979798,
            48,
            28,
            48,
            28,
            48
        ],
        [
            53.09090909090909,
            50.464646464646464,
            63.39393939393939,
            63.5959595959596,
            54.505050505050505,
            58.141414141414145,
            52.484848484848484,
            56.525252525252526,
            50.26262626262626,
            44,
            61.17171717171718,
            54.303030303030305,
            45.21212121212121,
            47.23232323232323,
            55.717171717171716,
            58.34343434343434,
            58.54545454545455,
            51.07070707070707,
            45.41414141414141,
            45.81818181818182,
            44.2020202020202,
            51.27272727272727,
            60.161616161616166,
            50.868686868686865,
            60.96969696969697,
            46.62626262626263,
            59.35353535353535,
            60.36363636363636,
            46.02020202020202,
            47.43434343434343,
            52.888888888888886,
            48.24242424242424,
            46.42424242424242,
            45.61616161616162,
            57.333333333333336,
            53.292929292929294,
            58.74747474747475,
            58.94949494949495,
            56.32323232323232,
            59.95959595959596,
            55.313131313131315,
            59.55555555555556,
            56.121212121212125,
            57.93939393939394,
            61.77777777777778,
            55.91919191919192,
            62.98989898989899,
            59.151515151515156,
            54.101010101010104,
            44.80808080808081,
            63.1919191919192,
            53.898989898989896,
            48.84848484848485,
            45.01010101010101,
            52.08080808080808,
            46.22222222222222,
            50.06060606060606,
            51.87878787878788,
            48.44444444444444,
            52.686868686868685,
            48.04040404040404,
            51.676767676767675,
            49.05050505050505,
            49.25252525252525,
            54.70707070707071,
            50.666666666666664,
            62.38383838383838,
            61.57575757575758,
            59.75757575757576,
            55.111111111111114,
            60.56565656565657,
            61.97979797979798,
            47.63636363636363,
            48.64646464646464,
            61.37373737373737,
            47.03030303030303,
            57.131313131313135,
            47.83838383838384,
            56.72727272727273,
            63.7979797979798,
            62.18181818181819,
            62.58585858585859,
            56.92929292929293,
            49.45454545454545,
            49.656565656565654,
            52.282828282828284,
            60.76767676767676,
            62.78787878787878,
            53.696969696969695,
            46.82828282828283,
            64,
            57.73737373737374,
            51.474747474747474,
            55.515151515151516,
            49.858585858585855,
            53.494949494949495,
            44.4040404040404,
            44.60606060606061,
            57.535353535353536,
            54.90909090909091,
            44,
            44,
            64,
            64
        ]
    ],
    "y_samples": [
        [
            -13.4548,
            -76.7973508,
            300.6403356,
            319.2335356,
            70.1883713099999,
            186.68782814,
            33.19122608,
            162.64082673,
            -11.41278588,
            -187.9992,
            336.38666834,
            141.1561266,
            -124.45802718,
            -53.44941051,
            217.66655676,
            310.41320502,
            328.51061965,
            105.37170501,
            -63.2613667600001,
            -41.2218211200002,
            -83.7502392000001,
            153.15490248,
            451.90701504,
            160.68501455,
            502.76319045,
            41.02252815,
            473.65225875,
            519.4340562,
            48.8834633199999,
            106.05898998,
            301.42766734,
            152.91005424,
            99.9914833199998,
            81.36312054,
            499.13763771,
            369.01930803,
            572.18294325,
            591.21582765,
            509.43154176,
            651.27849648,
            495.74089848,
            660.84392368,
            547.57075776,
            625.61697386,
            778.91508642,
            574.09345528,
            849.07604171,
            717.87957735,
            539.445397,
            198.1821819,
            907.6745819,
            564.493397,
            380.91637735,
            242.21044171,
            526.41705528,
            307.80108642,
            468.03737386,
            550.00115776,
            424.07592368,
            603.21889848,
            427.43849648,
            583.77394176,
            487.78622765,
            505.92134325,
            739.12330803,
            583.98723771,
            1078.52832054,
            1057.57548332,
            994.12685424,
            811.32646734,
            1052.32338998,
            1124.43546332,
            526.7144562,
            579.51625875,
            1135.96972815,
            529.42799045,
            976.84181455,
            583.63021504,
            982.25050248,
            1304.5345608,
            1246.04777888,
            1276.53583324,
            1037.09410501,
            713.96421965,
            733.04240502,
            861.70295676,
            1257.25538949,
            1361.60877282,
            958.1305266,
            653.15586834,
            1455.6352,
            1178.08001412,
            897.99522673,
            1097.43962608,
            842.85062814,
            1024.52597131,
            604.4787356,
            623.0719356,
            1250.0770492,
            1135.6368,
            -268,
            612,
            292,
            1572
        ]
    ]
}
